// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: pb/svc/test/test.proto

package test

import (
	common "github.com/example/test/pb/unit/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Some string `protobuf:"bytes,1,opt,name=some,proto3" json:"some,omitempty"`
}

func (x *GreetingReq) Reset() {
	*x = GreetingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_test_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingReq) ProtoMessage() {}

func (x *GreetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_test_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingReq.ProtoReflect.Descriptor instead.
func (*GreetingReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *GreetingReq) GetSome() string {
	if x != nil {
		return x.Some
	}
	return ""
}

type GreetingRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *common.ReturnMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GreetingRes) Reset() {
	*x = GreetingRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_test_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingRes) ProtoMessage() {}

func (x *GreetingRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_test_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingRes.ProtoReflect.Descriptor instead.
func (*GreetingRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_test_test_proto_rawDescGZIP(), []int{1}
}

func (x *GreetingRes) GetResult() *common.ReturnMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_pb_svc_test_test_proto protoreflect.FileDescriptor

var file_pb_svc_test_test_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x70, 0x62, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x21, 0x0a, 0x0b, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f,
	0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0b, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x46, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x08,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x42, 0x40, 0x0a, 0x17,
	0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x50, 0x01, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_test_test_proto_rawDescOnce sync.Once
	file_pb_svc_test_test_proto_rawDescData = file_pb_svc_test_test_proto_rawDesc
)

func file_pb_svc_test_test_proto_rawDescGZIP() []byte {
	file_pb_svc_test_test_proto_rawDescOnce.Do(func() {
		file_pb_svc_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_test_test_proto_rawDescData)
	})
	return file_pb_svc_test_test_proto_rawDescData
}

var file_pb_svc_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_svc_test_test_proto_goTypes = []interface{}{
	(*GreetingReq)(nil),      // 0: pb.svc.test.GreetingReq
	(*GreetingRes)(nil),      // 1: pb.svc.test.GreetingRes
	(*common.ReturnMsg)(nil), // 2: pb.unit.common.ReturnMsg
}
var file_pb_svc_test_test_proto_depIdxs = []int32{
	2, // 0: pb.svc.test.GreetingRes.result:type_name -> pb.unit.common.ReturnMsg
	0, // 1: pb.svc.test.Test.Greeting:input_type -> pb.svc.test.GreetingReq
	1, // 2: pb.svc.test.Test.Greeting:output_type -> pb.svc.test.GreetingRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_svc_test_test_proto_init() }
func file_pb_svc_test_test_proto_init() {
	if File_pb_svc_test_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_test_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_test_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetingRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_test_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_test_test_proto_goTypes,
		DependencyIndexes: file_pb_svc_test_test_proto_depIdxs,
		MessageInfos:      file_pb_svc_test_test_proto_msgTypes,
	}.Build()
	File_pb_svc_test_test_proto = out.File
	file_pb_svc_test_test_proto_rawDesc = nil
	file_pb_svc_test_test_proto_goTypes = nil
	file_pb_svc_test_test_proto_depIdxs = nil
}
